version: 2
jobs:
  go:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.11
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - run: ./internal/ci/init_gcloud
      - run: ./internal/ci/go_test
  rust:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.11
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          key: cargo-cache
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - save_cache:
          key: cargo-cache
          paths:
              - ~/.cargo
      - run: ./internal/ci/rust_test
  geth:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.11
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - run: ./internal/ci/ethereum_test
  truffle:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.11
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
      - run: ./internal/ci/truffle_test
  gui:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.11
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
      - run: ./internal/ci/init_gcloud
      - run: ./internal/ci/gui_test
  reportcoverage:
    docker:
      - image: smartcontract/deployer:latest
    steps:
      - checkout
      - run: ./internal/ci/init_gcloud
      - run: ./internal/ci/report_coverage
  deploy:
    docker:
      - image: smartcontract/deployer:latest
    environment:
      ENVIRONMENT: release
      DOCKER_TAG: staging
    steps:
      - checkout
      - run: ./internal/ci/init_gcloud
      - setup_remote_docker
      - run: echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run: make docker
      - run: make dockerpush
      - run: |
          docker inspect --format='{{index .RepoDigests 0}}' "smartcontract/chainlink:staging" \
            | awk -F'@' '{print$2}' \
            | xargs -I'%' kubectl set image deployment.apps/chainlink-deploy \
                "chainlink=smartcontract/chainlink:staging@%"


workflows:
  version: 2
  test:
    jobs:
      - go
      - truffle
      - geth
      - gui
      - rust
      - reportcoverage:
          requires:
            - go
            - gui
      - deploy:
          requires:
            - go
            - truffle
            - geth
            - gui
          filters:
            branches:
              only: master
